name: Main
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Print Go Version
      run: go version

    - name: Build
      run: |
        ./ci/build.sh

    - name: Test plugin
      run: |
        ./ci/test.sh plugin

    - name: Test tools
      run: |
        ./ci/test.sh tools

    - name: Compute Tag
      if: |
        github.event_name == 'push'
          && startsWith(github.event.ref, 'refs/tags/')
      id: compute_tag
      run: |
        tag=${GITHUB_REF#refs/tags/}
        if [ "$tag" != "$GITHUB_REF" ]; then
          tag=$(echo "$tag" | sed -e 's/[^a-zA-Z0-9\-\.]/-/g')
          echo ::set-output name=TAG::${tag}
        else
          echo "unable to determine tag" >&2
          exit 1
        fi

    - name: Release
      if: |
        github.event_name == 'push'
          && startsWith(github.event.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./ci/release.sh "${{ steps.compute_tag.outputs.TAG }}"
        assets=()
        for asset in $(ls releases); do
          assets+=("-a" "$asset")
        done
        hub release create "${assets[@]}" \
          -m "${{ steps.compute_tag.outputs.TAG }}" \
          "${{ steps.compute_tag.outputs.TAG }}"

    - name: Docker Release
      if: |
        github.event_name == 'push'
          && startsWith(github.event.ref, 'refs/tags/')
      run: |
        VERSION="${{ steps.compute_tag.outputs.TAG }}" ./ci/docker.sh